name: Deploy on pull requests

# Run on all pull requests or manually
on:
  pull_request: {}
  
  workflow_dispatch:

env:
  RENV_PATHS_ROOT: ~/.local/share/renv
  SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
  SHINY_APP_NAME: ${{ secrets.SHINY_APP_NAME }}
  SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
  SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
  NAME_OF_YOUR_PROJECT_PASSWORD: ${{secrets.NAME_OF_YOUR_PROJECT_PASSWORD}}

jobs:
  
  build:
    
    runs-on: macos-latest

    steps:
      
      - uses: actions/checkout@v3
      
      - name: Cache packages
        uses: actions/cache@v3
        with:
            path: ${{ env.RENV_PATHS_ROOT }}
            key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
            restore-keys: |
                ${{ runner.os }}-renv-
                
      - name: Restore packages
        shell: Rscript {0}
        run: |
            if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
            renv::restore()
      - name: Execute
        shell: Rscript {0}
        run: |
            source("deploy.R")
